theme: jekyll-theme-minimal
title: 'BIS 180L'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  # - heading: Introduction
  # - title: Introduction to the Workshop and the Core
  #   url: base/welcome
  # - title: Schedule
  #   url: base/schedule

  # - heading: Support
  # - title: Slack
  #   url: base/slack
  # - title: Zoom
  #   url: base/zoom
  # - title: Cheat Sheets
  #   url: base/cheatSheetIndex
  # - title: Windows 10/11 and Mac installation
  #   url: base/windows_and_mac

  - heading: CLI
  - title: Introduction to the Command Line 1
    url: cli/command-line-intro1
  - title: Introduction to the Command Line 2
    url: cli/command-line-intro2
  - title: Introduction to the Command Line 3
    url: cli/command-line-intro3
  - title: Extra
    url: cli/extra
  - title: BashCrawl
    url: https://gitlab.com/slackermedia/bashcrawl
  # - title: Challenge & Homework Solutions
  #   url: cli/solutions

  - heading: Software Installation
  - title: Installation using make and cmake
    url: cli/software
  - title: Conda
    url: cli/conda

  - heading: Introduction to R
  - title: Introduction to R Day 1
    url: R/Intro2R_day1
  - title: Introduction to R Day 2
    url: R/Intro2R_day2
  - title: Introduction to R Day 3
    url: R/Intro2R_day3

  - heading: Alignment
  - title: Local Alignment
  - url: alignment/instructions


  # - title: Challenge solutions
  #   url: R/challenge_solutions

  # - heading: ETC
  # - title: Github page
  #   url: https://github.com/ucdavis-bioinformatics-training/2024-June-Introduction-to-the-Command-Line-for-Bioinformatics
  # - title: Biocore website
  #   url: http://bioinformatics.ucdavis.edu
